- hosts: grupo
  remote_user: root
  
  # vars:
  #  una_variable: valordevar1
  
  tasks:
    - name: "Instalar PostgreSQL"
      
      apt:
        name: postgresql
      register: salidayum
    
    - debug: var=salidayum
   
